
== Changelog for domibusConnector-4.2.x

=== 4.2.0

==== Upgrade Manual:
link:upgrade/upgrade-4.2.0.html[Upgrade to 4.2.0]

==== Changes
* Loopback message sending support
* Support for distributed timer jobs (needed for cluster setup)
* Monitoring/Logging link:doc/logging.html[Logging Manual]
** Integration of spring-actuator (for monitoring)
** Integration of spring-sleuth (to improve/enable distributed monitoring with backend eg. e-Evidence RI)
* Packaging:
** Packaged with web based documentation (as part of the distribution package)
** Standalone Package (as part of the Distribution package)
** Docker assembly (available via nexus: https://secure.e-codex.eu/nexus/content/groups/public/eu/domibus/connector/domibusConnectorStandaloneLauncher/<version>/domibusConnectorStandaloneLauncher-<version>-docker-assembly.zip)
* Admin UI:
** Refreshable lists: relevant lists in UI get a "Refresh" button.
** Certificate information to be displayed.
** Multiple UI enhancements
** Fixing a SessionHijack Attack vector within UI
* Bugfixes/Security Improvements:
** Multiple updates/enhancements on database handling of p-Mode handling
** Removed Java de-/serialization from connector code
* ETSI-REM evidence handling: generated evidences to be sent back to backend/client using the known IDs. link:domibusConnectorAPI/interface_description.html[Interface Description]

==== Compatibility:
* The 4.2.x connector is compatible with the 4.1.3-RELEASE of the domibus-connector-plugin-Distribution (available via nexus: https://secure.e-codex.eu/nexus/content/groups/public/eu/domibus/connector/plugin/domibus-connector-plugin-Distribution/4.1.3-RELEASE/)

* Also all connector backends build against the domibusConnectorAPI from version 4.0 to 4.2 are compatible, since there have been no
API changes!

* The 4.2.x connector is compatible with all other 4.x connectors on e-Codex Message level.

==== Testing:

The Connector has been tested on

|===
| OS | Java | Application Server | Database Connector | Database

| AIX
| IBM JRE8
| Tomcat 8.5.x
| Ojdbc7
| Oracle 18c

| Windows 10
| Adopt Open JDK 1.8.x
| Tomcat 8.5.x
| H2 4.200 / Ojdbc8
| H2 Database 4.200 / Oracle Express 11g

| Ubuntu 18.0.4 LTS
| Open JDK 1.8.x
| Tomcat 8.5.x
| Mysql Connector 8.0.x
| Mysql 5.7.x

| Ubuntu 20.04 LTS
| Java 11.0.x
| Tomcat 9
| Mysql Connector 8.0.x
| Mysql 8.0.x

|===

Also special thanks to Maris (Latvia) for testing with Ubuntu and Mysql.


=== 4.2.1

==== Changes

* Documentation updates


=== 4.2.2

==== Changes

* Removed outdated pdfs from documentation
* Fix issue in update script for DC_PMODE_SET column active - added NOT NULL constraint + default value 0

=== 4.2.3

==== Changes

* Fix a typo in sql scripts

=== 4.2.4

==== Changes

* Fix a problem with mariadb/mysql in liquibase upgrade scripts in changeset with id 'create_p_mode_set_table_default_values'


=== 4.2.5

==== Changes

* Fix an issue within the initial mysql script: The column 'CONTENT_TYPE' within table 'DOMIBUS_CONNECTOR_MSG_CONT' should be of type VARCHAR(255) instead of BIGINT!

=== 4.2.6

==== Changes

* Fix Unicode Issues

=== 4.2.7

==== Changes

* Add stream closing interceptors to CXF Sending Proxies
* Fix an issue with missing UPPERCASE id column definition (@Column(name = "ID") is missing)

=== 4.2.8

==== Changes

* Added Fix which resolves a problem with an empty Business-Document wich lead to a NPE within DocumentBuilder.copyFromProperties
* Added Fix for database reporting scripts - now they are UPPER_CASE
* Add Pagination Support for MessagesList in UI to prevent Connector UI from starvation
because its loading ALL messages from DB
* Deactivated config change/save/reload support due unclear semantics/preconditions
* Fix typo within migration script at table: DC_TRANSPORT_STEP CONNECTOR_MESSSAGE_ID => should be CONNECTOR_MESSAGE_ID

=== 4.2.9

==== Changes

* Fixed sorting in Admin-UI "All Messages" list
* Fix: Adoptions to Messages View due to DB changes in 4.2
* Admin-UI: Show/Hide Columns in "All Messages" list and result list of "Search Messages"
* Fix: Timestamps of Evidences "DeliveredBackend/NationalSystem" and "DeliveredGateway" not set correctly
* Fix: OriginalSender/FinalRecipient in Evidences sent as own messages not set correctly
* Fix: Messages reports: not working if "include evidences as own messages" not set
* Feature: new property connector.controller.sendGeneratedEvidencesToBackend. If set to true, evidences that are triggered by the backend and generated by the connector are not sent back to the backend. Default is set to false.

=== 4.2.10

==== Changes

* Fix for Locking Problem which might occur on Mysql DBs under load

=== 4.2.11

==== Changes

* Fixed handling of partyRoles: roles are now taken into account wether it is an initiator or responder. Important for PModes where role for initiator and responder are different.
* Fix: upper/lower case bug in database script for generating reports with evidences as own messages. Concerns MySQL based DBMS (as those are case sensitive).

