
== Changelog for domibusConnector-4.3.x

=== 4.3.0

==== Changes

Upgrade manual: link:upgrade/upgrade-4.3.0.html[Upgrade to 4.3.0]

* Multiple improvements on the message flow to prevent dead locks, improve performance
* JTA integrated
* Pull-GW-Plugin: With the new Gateway plugin, the connector now can pull messages from GW (instead of push only)
* UI improvements:
** Backend Link Configuration
** Gateway Link Configuration
* New DB Scripts for (please also consult the test-matrix: link:doc/testing_matrix.html[Test Matrix]), (higher Major Versions might work)
** MariaDB 10.3
** Postgresql >= 13.2
** Mysql 8, >= 5.6.6
** Oracle 11g

=== 4.3.1

Skipped

=== 4.3.2

==== Changes

* Fix: File references remained open -> Files in fsstorage could not be deleted -> leads to "too many open files" exception after a while

=== 4.3.3

==== Changes

* Fixed handling of partyRoles: roles are now taken into account wether it is an initiator or responder. Important for PModes where role for initiator and responder are different.
* Fix: upper/lower case bug in database script for generating reports with evidences as own messages. Concerns MySQL based DBMS (as those are case sensitive).
