:path: ../../../

ifndef::basepath[]
:basepath: {path}
endif::basepath[]

ifndef::header[]
include::{basepath}/doc/header.adoc[]
endif::header[]


= Business document verification configuration

The business document which is sent by the backend is verified by the connector. 
This is either a digital signature on the business document PDF, or a generic verification.

The result is visualized within the TrustTokenPDF.

To be able to verify the business document, the domibusConnector requires to have access to the public key of the
certificate the digital signature was created with if there is one.

In case no digital signature is applied, there is also the opportunity to configure information on the advanced electronic system (AES),
the business document was received from.

== Import old config

This button gives the opportunity to import from your old configuration used for domibusConnector-4.2.x and domibusConnector-4.3.x.

It opens a dialog where the old configuration file (usually "connector.properties") can be uploaded.

After successful upload of the old configuration file, a read-only dialog is shown with the properties imported from the old config.

When the Button "Save Imported Config" is hit, a new Dialog shows the actual properties that get imported into the domibusConnector database. Their database target is the table DC_MESSAGE_LANE_PROPERTY.

This dialog has to be confirmed by hitting the "Check" Button.

Once approved, the imported configuration takes immediate effect.

The whole process can be interrupted any time by closing the dialog or by "Cancel" Button.

== Save/Reset Changes

The Configuration edited within this mask can be reset at any time hitting the "Reset Changes" Button.
This causes the configuration being reloaded and the mask being refreshed with the loaded configuration.

"Save Changes" causes the configuration to be stored into the domibusConnector database. Their database target is the table DC_MESSAGE_LANE_PROPERTY.

Once approved, the saved configuration takes immediate effect.

== Configuration properties

For configuring the check the following properties are available:

.e-Codex Business Document Verification Properties
|===
| property | description | field type | example values

| Country
| The country of the issuer of the TrustOKToken
| TextField
| The ISO-1366 2-digit country code.

| Service Provider
| Name of the Service Provider which has issued the Token (Who is operating the connector?)
| TextField
| Any value

| Allowed Advanced System Types
| Which AES Types are allowed. 
| Multi-Select-Box
a| * SIGNATURE_BASED: digital signatures are applied.
*  AUTHENTICATION_BASED: no digital signatures on the document.

| Default Advanced System Type
| Which AES should be used if the client has not requested the usage of a specific type with the message.
| Single-Select-Box
a| * SIGNATURE_BASED
*  AUTHENTICATION_BASED


| Allow client to set AdvancedSystemType on message
| The backend can specify the AES type used with every message. This property defines if this is allowed to override the "Default Advanced System Type".
| Checkbox
a| * set (true): if the backend sends an AES type with the message, this is chosen.
* not set (false): the "Default Advanced System Type" is chosen no matter if and what AES type comes with the message. 

| Authenticated Identity Provider
| In case AES AUTHENTICATION_BASED this Identity Provider is used for the TrustOKToken.
| TextField
| Any value

|===

The following properties will only be used in case of SIGNATURE_BASED AES type.

.Signature Validation Config
|===
| property | description | field type | example values

| Location of EtsiValidationPolicyXml
| The Location of the Etsi Validation Policy. This policy is used by the DSS Utils to verify the certificate of the attched signature on the business document.
| TextField
| by default a classpath reference.

| Use Trust Store
| Use an own TrustStore Configuration for verification.
| Checkbox
a| * set (true): the following properties deifine the TrustStore used for verification.
* not set (false): the trustStore imported with the PMode-Set will be used for verification. 

| Trust Store Configuration
| Configuration of the TrustStore used for verification. This Store should contain the public keys of certificates used for electronic signatures on business documents.
| Multiple fields
| Default TrustStore configuration fields.

| Use Ignore Store
| Use the Ignore Store, any certificate in here would be considered not trusted.
| Checkbox
a| * set (true): the following properties deifine the TrustStore with certificates ignored.
* not set (false): no TrustStore used with certificates ignored. 

| Ignore Store Configuration
| Configuration of the TrustStore containing certificates to be ignored (not trusted).
| Multiple fields
| Default TrustStore configuration fields.

| Set the trusted list source
| Any configured trusted list source can be set here as trust source. The certificates provided by this source will be considered as trusted.
| TextField
| Any value

| Should OCSP be used on certificate verification
| For this the checked certificate must provide a OCSP source address and the connector itself must be able to reach the OCSP source.
| Checkbox
a| * set (true)
* not set (false) 

| Should CRL be used on certificate verification
| For this the checked certificate must provide a CRL URL and the connector itself must be able to reach the provided CRL URL.
| Checkbox
a| * set (true)
* not set (false) 

|===

//== Upload any signed document and see the certificate validation result

//This section allows you to upload any document to see which result would be generated. Only the saved settings from above will be used for this process.