
:path: ../../../

ifndef::basepath[]
:basepath: ../../../
endif::basepath[]

ifndef::header[]
include::{basepath}/doc/header.adoc[]
endif::header[]

= Processing of an incoming business message

This chapter shows the example of an incoming business message. That means, that a business message is delivered
by the gateway.

== Message from gateway to the domibusConnectorController message queue

The following diagram shows how a message that is sent to the domibusConnector is transported to the domibusConnectorController message queue.

[plantuml,message_proc_in_business_1,format=svg]
----
@startuml


top to bottom direction
skinparam monochrome false
skinparam linetype ortho



package domibusConnectorAPI{
	interface DomibusConnectorGatewayDeliveryWebService
	interface DomibusConnectorGatewayWebService
}

package domibusConnectorLink{
	component DCGatewayWebServiceClient
	component WsGatewayPluginDeliveryServiceEndpoint
	interface SubmitToConnector
	
}

queue toConnectorControllerQueue

DomibusConnectorGatewayWebService --> DCGatewayWebServiceClient : link.gwwspullplugin profile
DCGatewayWebServiceClient --> SubmitToConnector

DomibusConnectorGatewayDeliveryWebService --> WsGatewayPluginDeliveryServiceEndpoint : link.wsgatewayplugin profile
WsGatewayPluginDeliveryServiceEndpoint --> SubmitToConnector
SubmitToConnector --> toConnectorControllerQueue

@enduml
----

Before the message is submitted to the queue it is transformed to the internal domain model. During this transformation the payload is handled by the link:../payload_handling.html[Large File Persistence Service].

== Message processing in domibusConnectorController

The following diagram shows how a message that is put on the toConnectorController queue is processed

[plantuml,message_proc_in_business_2,format=svg]
----
@startuml


top to bottom direction
skinparam monochrome false
skinparam linetype ortho




queue toConnectorControllerQueue
queue DLQ.toConnectorControllerQueue

queue submitToLinkQueue

package domibusConnectorController {
	package JTATransaction_Connector {
	    component ToConnectorControllerListener
	    component ToBackendBusinessMessageProcessor
	    component LookupBackendNameStep
	    component MessageConfirmationStep
	    component SubmitConfirmationAsEvidenceMessageStep
	    component ResolveECodexContainerStep
	    component SubmitMessageToLinkModuleQueueStep
	}
	
}


toConnectorControllerQueue --> ToConnectorControllerListener
ToConnectorControllerListener --> ToBackendBusinessMessageProcessor : For a business message from gateway to backend
ToBackendBusinessMessageProcessor -d-> LookupBackendNameStep : identify target backend
ToBackendBusinessMessageProcessor -d-> MessageConfirmationStep : create RELAY_REMMD evidence
ToBackendBusinessMessageProcessor -d-> SubmitConfirmationAsEvidenceMessageStep : sent evidence back
ToBackendBusinessMessageProcessor -d-> ResolveECodexContainerStep : resolve ASIC-S
ToBackendBusinessMessageProcessor -d-> SubmitMessageToLinkModuleQueueStep : send to backend
SubmitMessageToLinkModuleQueueStep -d-> submitToLinkQueue : on success
JTATransaction_Connector -d-> DLQ.toConnectorControllerQueue : on failure

@enduml
----

== Message send from the domibusConnector to the backend

The following diagram shows how a message that is put on the submitToLink queue is processed

[plantuml,message_proc_in_business_3,format=svg]
----
@startuml


top to bottom direction
skinparam monochrome false
skinparam linetype ortho



package domibusConnectorAPI{
	interface DomibusConnectorBackendDeliveryWebService
}

package domibusConnectorLink{
	
	package JTATransaction_ToLink {
	  component ToLinkPartnerListener
	  component SubmitToLinkService
		component WsBackendSubmitTo
	}
}


queue submitToLinkQueue
queue DLQ.submitToLinkQueue


JTATransaction_ToLink -d-> DLQ.submitToLinkQueue : on failure
submitToLinkQueue -d-> ToLinkPartnerListener
ToLinkPartnerListener -d-> SubmitToLinkService
SubmitToLinkService --> WsBackendSubmitTo : to backend
WsBackendSubmitTo --> DomibusConnectorBackendDeliveryWebService : LinkMode.PUSH
WsBackendSubmitTo -d-> exit : makeMessageReadyForPull

@enduml
----


.Process Incoming Business Message (GW2CON)
[plantuml,confirmation_message_sequence_diagram,format=svg]
----
@startuml

actor GW


box "Connector"
participant LinkModule
participant DTOtoDomain
collections ConnectorController
participant LargeFileProvider
participant MessageTransportStateService

end box
participant JMS
database DB
participant FS

actor BACKEND

GW -> LinkModule++: deliverMessage
LinkModule -> DTOtoDomain--++: transformToDomainModel
loop for every attachment
DTOtoDomain -> LargeFileProvider--++: persist large file
end
LargeFileProvider -> FS: write to filesystem
LargeFileProvider --> DTOtoDomain--++: return LargeFile reference
DTOtoDomain --> LinkModule--++: return DomainModel Message
LinkModule -> JMS: put on Queue
LinkModule --> GW--: return ACK

ref over JMS
  DomainMessage is on
  JMS queue
end ref

JMS -> ConnectorController++:

group JTA_TX

ConnectorController -> ConnectorController: verifyPModesStep
ConnectorController -> ConnectorController: lookupBackendNameStep
ConnectorController -> ConnectorController: createNewBusinessMessageInDBStep
ConnectorController -> ConnectorController: processTransportedConfirmations

ConnectorController -> ConnectorController: createRelayREMMD
ConnectorController -> ConnectorController: process relayREMMD evidence
ConnectorController -> JMS: submitOppositeDirection(relayREMMD evidence)\n put it on toLinkQueue
ConnectorController -> ConnectorController: resolve ecodex Container
alt
ConnectorController -> JMS: submitMessage(message)\n put it on toLinkQueue

else if a SecurityException happens (invalid eCodexContainer)

ConnectorController -> ConnectorController: createNonDeliveryEvidence
ConnectorController -> ConnectorController: process NonDelivery evidence
ConnectorController -> JMS: submitOppositeDirection(NonDelivery evidence)\n put it on toLinkQueue

end

end group


JMS -> LinkModule++: send evidence back to GW
LinkModule -> GW++: submit evidence message
GW --> LinkModule--: return EBMSID and ack / nack
group JTA_TX
LinkModule -> MessageTransportStateService--++: updateTransportState(EBMSID, ack/nack)
MessageTransportStateService -> DB: persist transport state
MessageTransportStateService --> LinkModule--: return TransportId
end




@enduml
----

=== Possible Problems/Flaws and Discussion

* In the error case the NON_DELIVERY evidence could overtake the RELAY_REMMD evidence. This should not be a big problem since the DELIVERY/NON_DELIVERY evidence has a higher priority and a positive RELAY_REMMD evidence cannot change the message state. Though the evidence chain is not complete.
* In case of any error aside a DomibusConnectorSecurityException the message will end on error queue (after some retries). Here the message should terminate in an NON_DELIVERY/RELAY_REMMD_REJECTION after some retries. This behaviour should reduce the number of needed manual interference. Though it must be configurable to respect national requirements.
* Maybe it is better instead of creating the NON_DELIVERY evidence in this process using a trigger so the evidence is created by the Confirmation Message Processor. This will not be possible for the RELAY_REMMD evidence because this must be sent as part of the BusinessMessage to the backend.