rootProject.name = "domibusConnector"
include(":domibusConnectorDssToolkit")
include(":domibusConnectorUILib")
include(":domibusConnectorBuilderStandalone")
include(":domibusConnectorControllerAPI")
include(":domibusConnectorPersistence")
include(":domibusConnectorDocumentation")
include(":domibusConnectorAPI")
include(":domibusConnectorDistribution")
include(":domibusConnectorControllerLIB")
include(":domibusConnectorBuilder")
include(":domibusConnectorEvidencesToolkit")
include(":domibusConnectorAPIlib")
include(":domibusConnectorController")
include(":domibusConnectorStarter")
include(":domibusConnectorLink")
include(":domibusConnectorTestData")
include(":domibusConnectorSecurityToolkit")
include(":domibusConnectorBuilderDeployable")
include(":domibusConnectorUI")
project(":domibusConnectorBuilderStandalone").projectDir = file("domibusConnectorBuilder/domibusConnectorBuilderStandalone")
project(":domibusConnectorBuilderDeployable").projectDir = file("domibusConnectorBuilder/domibusConnectorBuilderDeployable")
