:path: ../../../

ifndef::basepath[]
:basepath: ../../../
endif::basepath[]

ifndef::header[]
include::{basepath}/doc/header.adoc[]
endif::header[]


= PModes data in domibusConnector


== PMode-Set definition

Every business use-case handled using e-CODEX needs to be configured in processing modes.
Those processing modes, in short PModes, hold all relevant information on the business use-case definition, the participating members and security configuration necessary to establish gateway to gateway communication over e-CODEX.

Most PModes are nowadays configured using the Configuration Management Tool (CMT).

Once a PMode-Set is generated by the CMT and downloaded it can be used.

== Connector relevant information in PMode-Sets

PMode-Sets downloaded from the CMT do contain a lot more information than the domibusConnector actually needs to process business messages for certain business use-cases.

Therefore, the domibusConnector only needs the information out of 2 files of the PMode-Set:

* The pmodes XML file itself
* The connectorstore

=== The contents of the PModes file

The PModes.xml (name can vary depending on the configuration definition) holds a lot of information about the use-cases, participants, security settings and processing legs.
Not everything is required to be used within the domibusConnector.
Though, some of the information is used by the domibusConnector to validate the data of a business message and to support the message routing of the AS4 gateway(s).

=== The connectorstore

The connectorstore within a PMode-Set is a truststore holding the public certificates of the participating members which are used to validate the signatures on the ASIC-S containers received. As the connectorstore is part of every PMode-Set and contained certificates may have changed, it is coupled with the PModes at the level of import.

=== Data from the PModes XML file imported and used by the domibusConnector

[cols="10%,10%,20%,40%,20%"]
|===
|Section in XML | Example | Target in DB | Mapping-to-datamodel | description

|services
m|<service name="ConTESTService" value="Connector-TEST" type="urn:e-codex:services:"/>
m|DOMIBUS_CONNECTOR_SERVICE
a| * value=SERVICE
 * type=SERVICE_TYPE
|The Service and Service-type defines the business use-case(s) configured within the PModes.

|actions
m|<action name="ConTESTActionTestForm" value="ConTest_Form"/>
m|DOMIBUS_CONNECTOR_ACTION
a| * value=ACTION
|The actions define steps of a procedure within business use-cases. They are sub-sets of services.

|parties
m|<party name="service_ctp" endpoint="https://someURL:somePort/contextPath" allowChunking="false">
				<identifier partyId="CTP" partyIdType="unregistered"/>
			</party>
m|DOMIBUS_CONNECTOR_PARTY
a| * name=IDENTIFIER
 * partyId=PARTY_ID
 * partyIdType=PARTY_ID_TYPE - points to the definition of paryIdTypes in XML file
|The parties are the actual members participating. Each party defines a gateway connected to the e-CODEX network within this PModes definitions.

|roles
m|<role name="defaultInitiatorRole" value="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/initiator"/>
			<role name="defaultResponderRole" value="http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/responder"/>
m|DOMIBUS_CONNECTOR_PARTY
a| * value=ROLE
|The roles are important for the definition of processes possible

|process
m|<process name="ConTESTProcess" agreement="agreementEmpty" mep="twoway" binding="pushAndPush" initiatorRole="defaultInitiatorRole" responderRole="defaultResponderRole">
m|DOMIBUS_CONNECTOR_PARTY
a| * initiatorRole=ROLE_TYPE.initiator
 * responderRole=ROLE_TYPE.responder
|Within the process definition sets of initiatorParties and responderParties are listed. A party that is listed as initiator gets the role type initiator and a party listed as responder gets the role type responder. This can lead to double definition of parties in the table relating to the PMode set. The domibusConnector resolves the role type itself and picks the correct party definition when a message is processed.

|===

