:path: ../../../

ifndef::basepath[]
:basepath: ../../../
endif::basepath[]

ifndef::header[]
include::{basepath}/doc/header.adoc[]
endif::header[]

= Connector-to-connector business message tests

This feature gives the opportunity to test the connection with another domibusConnector from
the e-CODEX participants that are part of the current active PMode-Set.


== Functionality of connector-to-connector tests

The connector to connector test feature sends a business message to another connector and is also
capable of receiving such test messages without the backend(s) to be involved.
Other than a simple connection test (like the DOMIBUS gateways' connection test or connection monitoring)
it also tests if messages can be processed the whole message processing flow as described in 
link:../architecture/connector_message_flow.html[connector_message_flow].

It processes a message the whole chain of process steps within the domibusConnector.

* At sending, it builds the ASIC-S container like described in link:../architecture/ecodex_container_creation.html[ecodex_container_creation].
* At sending, it generates a first ETSI-REM evidence (SUBMISSION_ACCEPTENCE).
* It transmits the message to another e-CODEX participant from the PModes.
* At receiving, it resolves and validates the ASIC-S container.
* At receiving, it generates all necessary ETSI-REM evidences and sends them back to the sender.

=== default-test-backend

To be able to test the whole message processing workflow, the domibusConnector at startup starts a 
default backend plugin. This default backend does not need to be configured. It is started also with a new 
installation that does not have any backend links configured yet.

The default-test-backend is placed behind the message queue that transmits messages between backend links and the 
domibusConnectorController.

All messages identified as connector-to-connector test messages are sent automatically to that default-test-backend.
The default-test-backend will NOT send those messages to any backend, but triggers the process to send a DELIVERY
ETSI-REM evidence back to the sender of the message.

When sending a connector-to-connector test message, the message is sent over the default-test-backend to the 
domibusConnectorController where it is processed like any other business message that would be received from a 
backend.

=== Preconditions

To be able to use this feature, the following preconditions must be met:

* An active PMode-Set must be imported
* The key/truststores for processing must be configured. Like the security container stores and evidence builder store.
* The connection to the gateway must be configured and active.
* The gateway to gateway connection to other e-CODEX partners must be set up and confirmed.
* The active PMode-Set must have the "Connector-TEST" service with action "ConTest_Form" configured. All PModes generated by the CMT should meet 
this condition already.


