:path: ../../../

ifndef::basepath[]
:basepath: ../../../
endif::basepath[]

ifndef::header[]
include::{basepath}/doc/header.adoc[]
endif::header[]

= Sending a connector-to-connector test message

The user interface of the domibusConnector offers the possibility to easily create and send connector-to-connector test messages.

When entering the view "Connector Tests -> Send Connector Test Message" a reduced message form is displayed.
Only message contents that are required for such a connector-to-connector test are to be filled.

== Filling the message details for a connector-to-connector test message

.ConnectorTestMessageDetails
|===
|Field name |Description |Required |Pre-set data

|Conversation ID
|The conversation ID given to the test message. May help to find the message on the receiving side
|no
|empty

|Backend Message ID
|The backendMessagId given to the test message. May be overwritten but must be unique over all messages on the domibusConnector.
|yes
|a new ID generated by the domibusConnector

|Original Sender
|Can be of any value.
|yes
|empty

|Final Recipient
|Can be of any value.
|yes
|empty

|ToParty
|A selection box with all Parties from the active PMode-Set with roleType initiator. Here, the receiver of the message must be chosen.
|yes
|empty

|Service
|The service for connector test messages from the active PMode-Set. Only readable.
|yes
|Connector-TEST

|Action
|The action for connector test messages from the active PMode-Set. Only readable.
|yes
|ConTest_Form

|From Party
|The party from the active PMode-Set that was identified as this connector's and gateway's party.
|yes
|PartyId and PartyIdType identified as "home" party.

|===

== Files to be added to the message

As the connector-to-connector test message is treated as a business message, it also must match the requirements any business message must meet.

To be able to test the whole functionality of message processing, the following files MUST be added

* A business content file. It is an XML file of any content. The content is not validated during processing.
* A business document file. It is a PDF file of any content. As all test messages are treated AUTHENTICATION_BASED no signature needs to be applied to this document.

=== Set default files

The domibusConnector offers the possibility to add the mandatory files with a simple click here.

=== Add File to message

Here, any file can be added to the message. If the default files are not used, a business content XML and business document PDF 
must be added. 
It also gives the possibility to add any business attachment to the message.

== Submit Message

If "Submit Message" button is hit, the message created here is first validated on completeness.
If not complete, the user gets informed what is missing.

Once validation is successful, the message is sent to the default-test-backend and processed.
In the end, it is submitted to the target.
