:path: ../../

ifndef::basepath[]
:basepath: ../../
endif::basepath[]

ifndef::header[]
include::{basepath}/doc/header.adoc[]
endif::header[]

= Payload Handling / Large File Handling

As the messages can be big the connector offloads the payload of messages into a storage. There is support for multiple storages.

The configuration is described here: link:../configuration/large_file_storage_configuration.adoc[Large File Handling Configuration]

Streaming support means that the content of the file is streamed into the application and also written out of the application as stream. This approach consumes much less heap space than storing the file content into a byte array as it is done by the JPABased implementation.

== Class diagram

The main entry point for using the storage sytem is the DCBusinessDomainPersistenceService. This services offers to create, get, delete a Storage reference.


[plantuml,storage_architecture,format=svg]
----
@startuml

interface DCBusinessDomainPersistenceService

class DCBusinessDomainPersistenceServiceImpl

DCBusinessDomainPersistenceServiceImpl -u-> DCBusinessDomainPersistenceService

interface LargeFilePersistenceProvider

class LargeFilePersistenceServiceFilesystemImpl

class LargeFilePersistenceServiceJpaImpl

LargeFilePersistenceServiceJpaImpl -u-> LargeFilePersistenceProvider
LargeFilePersistenceServiceFilesystemImpl -u-> LargeFilePersistenceProvider


DCBusinessDomainPersistenceServiceImpl "1" -r- "*"  LargeFilePersistenceProvider

@enduml
----

== Large File Provider Implementations

Currently 2 storage implementations are available:

=== FileSystemStorage (supports streaming)

The filesystem storage stores the content on the filesystem. Optional a encryption of the content is supported. The encryption key is stored in the returned LargeFileReferenceObject. Since this object becomes part of the message process (DomibusConnectorMessage class) it is put on the JMS queue and database.

The storage follows this organisation:

* <basepath>/<connector_messageid>/<storage_item_1>
* <basepath>/<connector_messageid>/<storage_item_2>

With this organisation after a message has been completly processed the <basepath>/<connector_message_id> folder can be deleted.

==== Deletion

The deletion happens in 2 steps.

1. Deleting the password from DB and commit DB change
2. Delete file on disk
3. Mark file as deleted in DB and commit DB change

=== JPABased Database Storage (Does NOT support streaming)

The JPA storage stores the content into the database. For this JPA mapping is used. The implementation needs to load the complete file into a byte array before writing it into the database. Also when the content is read the whole file is stored into a byte array. So this storage engine should not used if large files are expected.

== Discussion

In the future it is planned to implement that the used storage engine is chosen by the size of the content. So small content can still be handled completely in memory and larger content is automatically written to filesystem. This approach should avoid the file and network overhead for small files.

It might also be useful to support a bucket storage like S3. This could be nice feature for HA environments.
