:path: ../../

ifndef::basepath[]
:basepath: ../../
endif::basepath[]

ifndef::header[]
include::{basepath}/doc/header.adoc[]
endif::header[]

= Storage, Encryption and Deletion of Payload, Addressing and other Data


== Kinds of Data processed by the connector

Within the connector the data is categorized in the following groups:

* Adressing Data / AS4 Data
* Payload Data
* Legal Data / Proof of communication, recipient, sent
* Technical Data / Log Data

== Addressing Data / AS4 Data

The addressing data or AS4 data is describing the recipient and the business process itself. The following fields fall under this category.
For more details consult the eDelivery profile and the eCodex protocol specification.

* ToParty
** PartyId
** PartyIdType
** PartyRole
* FromParty
** PartyId
** PartyIdType
** PartyRole
* FinalRecipient
* OriginalSender
* ConversationID
* EBMSID
* RefToMessageId

All this data is stored by the connector within the database. There is no purge or deletion mechanism in place. So the products or usecases which are using the connector should make sure that no sensitive data is used within this fields.

NOTE: In some backend systems the case number (or parts of it) is used as a conversation id. So if the case number is considered sensitive the backend system should not write the case id into the conversationId field. As the original sender and final recipient are already part of the public address book (criminal court database, civil court database, ...) this data can already be considered as public.

== Payload Data

The connector treats the following as payload data:

* AS4 container
* XML Business Document

The payload data is handled by the large file handling module. Currently the connector has 2 modules for that (for mor details see link:payload_handling.adoc[Payload Handling]) :

** FileSystem (Payload can be stored encrypted on disk, Password is stored in DB and JMS Broker)
** Database (Payload is written into DB)

The payload data is deleted if the message becomes rejected or accepted. This happens if for the message a negative evidence or positive evidence has been created or after 7 days. A timer job is checking periodically if a message payload should be deleted.

== Legal Data

The connector treats the following as legal data. This data is stored without time limit within the database. This data is used to proof the recipient/sent of a message.

* All kind of evidences
* TrustToken.pdf
* TrustToken.xml
* HashSums of all transported payload data

== Technical Data / Log Data

Logging is done by the log4j2 framework and configured within the log4j2.xml.
Passwords are only logged if the logging level is increased to TRACE.

For more information about logging see: link:../configuration/logging.adoc[Logging Configuration]






