<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions
        xmlns:tns="http://connector.ecodex.eu/jms/gateway/"
        xmlns:dct="transition.domain.connector.ecodex.eu"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        name="DomibusConnectorDeliveryService"
        targetNamespace="http://connector.ecodex.eu/jms/gateway/">

    <wsdl:import
            namespace="transition.domain.connector.ecodex.eu"
            location="eu.ecodex.connector.domain.transition/DomibusConnectorTransitionModel.xsd"/>

    <wsdl:message name="message">
        <wsdl:part name="message" type="dct:DomibusConnectorMessageType"/>
    </wsdl:message>
    <wsdl:message name="response">
        <wsdl:part name="response" type="dct:DomibusConnectorMessageResponseType"/>
    </wsdl:message>

    <wsdl:portType name="DomibusConnectorAsyncDeliverToConnectorService">
        <wsdl:operation name="deliverMessage">
            <wsdl:input message="tns:message"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:portType name="DomibusConnectorAsyncDeliverToConnectorReceiveResponseService">
        <wsdl:operation name="deliverResponse">
            <wsdl:input message="tns:response"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:portType name="DomibusConnectorAsyncSubmitToGatewayService">
        <wsdl:operation name="submitMessage">
            <wsdl:input message="tns:message"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:portType name="DomibusConnectorAsyncSubmitToGatewayReceiveResponseService">
        <wsdl:operation name="submitResponse">
            <wsdl:input message="tns:response"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
