//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.18 at 01:31:03 PM MESZ 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://uri.eu-spocs.eu/configuration/eDelivery", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.spocseu.edeliverygw.configuration.xsd;
