plugins {
    id("eu.domibus.connector.java-conventions")
}

dependencies {
    api(project(":domibusConnectorControllerLIB"))
    api(project(":domibusConnectorDssToolkit"))
    api(project(":domibusConnectorControllerAPI"))
    api(libs.org.springframework.spring.context)
    api(libs.org.springframework.spring.jdbc)
    api(libs.org.springframework.boot.spring.boot.autoconfigure)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    api(libs.org.springframework.boot.spring.boot.configuration.processor)
    api(libs.eu.europa.ec.joinup.sd.dss.dss.utils.apache.commons)
    api(libs.eu.europa.ec.joinup.sd.dss.dss.document)
    api(libs.eu.europa.ec.joinup.sd.dss.dss.service)
    api(libs.eu.europa.ec.joinup.sd.dss.dss.tsl.validation)
    api(libs.eu.europa.ec.joinup.sd.dss.dss.crl.parser.x509crl)
    api(libs.eu.europa.ec.joinup.sd.dss.dss.asic.xades)
    api(libs.eu.europa.ec.joinup.sd.dss.dss.token)
    api(libs.eu.europa.ec.joinup.sd.dss.dss.pades)
    api(libs.eu.europa.ec.joinup.sd.dss.dss.pades.pdfbox)
    api(libs.commons.lang.commons.lang)
    api(libs.eu.ecodex.utils.spring.boot.property.converter)
    api(libs.org.bouncycastle.bcpkix.jdk15on)
    api(libs.com.github.librepdf.openpdf)
    api(libs.jaxb.impl)
    api(libs.javax.validation.validation.api)
    testImplementation(libs.org.springframework.boot.spring.boot.test)
    testImplementation(libs.org.springframework.spring.test)
    testImplementation(libs.org.xmlunit.xmlunit.matchers)
    testImplementation(libs.org.xmlunit.xmlunit.core)
    testImplementation(libs.org.dbunit.dbunit)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.commons.cli.commons.cli)
    testImplementation(libs.jaxb.core)
    testImplementation(project(":domibusConnectorAPI"))
    testImplementation(libs.com.h2database.h2)
    testImplementation(libs.org.liquibase.liquibase.core)
    testImplementation(project(":domibusConnectorControllerAPI"))
    testImplementation(libs.eu.ecodex.utils.logging.tester)
    testImplementation(project(":domibusConnectorTestData"))
    testImplementation(libs.com.github.database.rider.rider.spring)
    testImplementation(libs.org.glassfish.jaxb.jaxb.runtime)
}

description = "The securityToolkitModule resolves and creates the ASIC-S Container. Its a bridge between the connector and the securityLib"
