insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DC_KEYSTORE.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DC_LINK_CONFIGURATION.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DC_LINK_PARTNER.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DC_MESSAGE_LANE.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DC_MSGCNT_DETSIG.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DC_PMODE_SET.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DC_TRANSPORT_STEP.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DOMIBUS_CONNECTOR_ACTION.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DOMIBUS_CONNECTOR_BIGDATA.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DOMIBUS_CONNECTOR_EVIDENCE.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DOMIBUS_CONNECTOR_MESSAGE.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DOMIBUS_CONNECTOR_MESSAGE_INFO.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DOMIBUS_CONNECTOR_MSG_CONT.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DOMIBUS_CONNECTOR_MSG_ERROR.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DOMIBUS_CONNECTOR_PARTY.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DOMIBUS_CONNECTOR_PROPERTY.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DOMIBUS_CONNECTOR_SERVICE.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DOMIBUS_CONNECTOR_USER.ID', 1000)/
insert into DOMIBUS_CONNECTOR_SEQ_STORE(SEQ_NAME, SEQ_VALUE) values ('DOMIBUS_CONNECTOR_USER_PWD.ID', 1000)
/
INSERT INTO DOMIBUS_CONNECTOR_USER (ID, USERNAME, ROLE, LOCKED, NUMBER_OF_GRACE_LOGINS, GRACE_LOGINS_USED, CREATED)
VALUES (1, 'admin', 'ADMIN', 0, 5, 0, current_timestamp)/
INSERT INTO DOMIBUS_CONNECTOR_USER_PWD (ID, USER_ID, PASSWORD, SALT, CURRENT_PWD, INITIAL_PWD, CREATED)
VALUES (1, 1,
        '2bf5e637d0d82a75ca43e3be85df2c23febffc0cc221f5e010937005df478a19b5eaab59fe7e4e97f6b43ba648c169effd432e19817f386987d058c239236306',
        '5b424031616564356639', 1, 1, current_timestamp)
/
INSERT INTO DOMIBUS_CONNECTOR_USER (ID, USERNAME, ROLE, LOCKED, NUMBER_OF_GRACE_LOGINS, GRACE_LOGINS_USED, CREATED)
VALUES (2, 'user', 'USER', 0, 5, 0, current_timestamp)/
INSERT INTO DOMIBUS_CONNECTOR_USER_PWD (ID, USER_ID, PASSWORD, SALT, CURRENT_PWD, INITIAL_PWD, CREATED)
VALUES (2, 2,
        '2bf5e637d0d82a75ca43e3be85df2c23febffc0cc221f5e010937005df478a19b5eaab59fe7e4e97f6b43ba648c169effd432e19817f386987d058c239236306',
        '5b424031616564356639', 1, 1, current_timestamp)
/
INSERT INTO DC_MESSAGE_LANE (ID, NAME, DESCRIPTION)
VALUES (1, 'defaultMessageLane', 'default message lane')
/

INSERT INTO DC_DB_VERSION (TAG)
VALUES ('V4.4.5')
/
