on:
  push:
  pull_request:
  merge_group:
name: CI Pipeline
jobs:
  CI:
    uses: e-CODEX/workflows/.github/workflows/maven-ci.yaml@main
    with:
      java-version: 21
      sbom-path: 'target/bom.xml'
      artifact-path: 'domibusConnectorDistribution/target/domibusConnector.zip'
