on: 
  push:
  pull_request:
  merge_group:
name: Java code Checkstyle
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@d8a9844b218a259bedd1b8ce4564a2fca7c66750 # v1.8.0
        with:
          reporter: github-pr-review
          level: warning
          checkstyle_config: google_checks.xml
