on: 
  push:
  pull_request:
  merge_group:
name: Java code Checkstyle
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@5e8071773caebb6d5bc7a57465185307808814f7 # v1.8.0
        with:
          reporter: github-pr-review
          level: warning
          checkstyle_config: google_checks.xml
