on: 
  push:
  pull_request:
  merge_group:
name: Java code Checkstyle
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@b80636f254f18c894aa0f2231c97a703e5020836 # v1.8.0
        with:
          reporter: github-pr-review
          level: warning
          checkstyle_config: google_checks.xml
