on: 
  push:
  pull_request:
  merge_group:
name: Java code Checkstyle
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@5751ddceff1848a4df6a2d9aa9e7fbc735be4ddb # v1.8.0
        with:
          reporter: github-pr-review
          level: warning
          checkstyle_config: google_checks.xml
