on: 
  push:
  pull_request:
  merge_group:
name: Java code Checkstyle
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@fa94d0fc8906953706f1b6af8f3729a4e4fe0c3a # v1.8.0
        with:
          reporter: github-pr-review
          level: warning
          checkstyle_config: google_checks.xml
