on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
  workflow_dispatch: 
name: Static Analysis Java    
jobs:
  sonar:
    uses: e-CODEX/workflows/.github/workflows/sonar-java.yaml@main
    with:
        java-version: 21
        build-tool: 'maven'
    secrets: inherit
  codeql:
    uses: e-CODEX/workflows/.github/workflows/codeql-java.yaml@main
    with:
      java-version: 21
      build-tool: 'maven'
  qodana:
    uses: e-CODEX/workflows/.github/workflows/qodana.yaml@main
    secrets: inherit